sensors.dynamic_sensor_hal.so
android.hardware.sensors@2.0-subhal-impl-1.0.so
/vendor/lib64/sensors.als_wrapper.so
/vendor/lib64/sensors.oplus_virtual.so
odm/lib64/oplus.sensors.ssc.so
/odm/lib64/libmxmafa.so
